### PR TITLE
Adds mutation observer to link new blocks when they are created

### PR DESCRIPTION
**Pull request by pedrovereza**
Links were only being added when the page loaded, so new comments with `typescript` blocks wouldn't be linked until the page refreshed. This pr fixes it 😄 

## Before

before

## After

after

### CODE REVIEW

**Comment by pedrovereza** [comment]
@orta let me know if that's useful 🙏

**Comment by orta** [comment]
Doh! Yep

**Comment by orta** [comment]
I missed this pr

**Comment by orta** [comment]
I’m on a phone but hopefully should remember to make a new build

**Pull request merged**
